### ISSUE TITLE
Meta: Move to API endpoint for content

### ISSUE THREAD

**Issue by kevee** [csumb/csumb-gatsby#292]
Instead of building content to a central flat file repository, pull content from the CSUMB editor using a regular JSON API. This should:

- Mean in-page nav and regular nav get updated correctly
- No more "floating" unpublished pages
- No more pages being left published.

- [x] Deploy to test
- [x] Sites
- [x] Navigation
- [x] Pages/events
- [x] Redirects

**Comment by kevee** [comment]
Cleanup package.json files for plugins.

**Comment by kevee** [comment]
Ref in editor: https://github.com/csumb/csumb/commit/e7920da0c3589d1dc88205adfc42958958182328

**Comment by kevee** [comment]
Issue:

navigation on /international is missing links
should be this https://csumb.edu/international

**Comment by kevee** [comment]
To do post launch:

**Immediately**
- [ ] disable hooks for publishing in node changes

**1 week later**
- [ ] delete most of the content from the web content repo
- [ ] remove github stuff from module
